@echo off
"C:\Qt\6.8.3\msvc2022_64\bin\moc.exe" "include\audio_processor.h" -o "src\moc_audio_processor.cpp" 
"C:\Qt\6.8.3\msvc2022_64\bin\moc.exe" "include\loading_dialog.h" -o "src\moc_loading_dialog.cpp" 
"C:\Qt\6.8.3\msvc2022_64\bin\moc.exe" "include\whisper_gui.h" -o "src\moc_whisper_gui.cpp"
"C:\Qt\6.8.3\msvc2022_64\bin\moc.exe" "include\subtitle_manager.h" -o "src\moc_subtitle_manager.cpp"
"C:\Qt\6.8.3\msvc2022_64\bin\moc.exe" "include\parallel_openai_processor.h" -o "src\moc_parallel_openai_processor.cpp"
"C:\Qt\6.8.3\msvc2022_64\bin\moc.exe" "include\result_merger.h" -o "src\moc_result_merger.cpp"
"C:\Qt\6.8.3\msvc2022_64\bin\moc.exe" "include\realtime_segment_handler.h" -o "src\moc_realtime_segment_handler.cpp"
"C:\Qt\6.8.3\msvc2022_64\bin\moc.exe" "include\voice_activity_detector.h" -o "src\moc_voice_activity_detector.cpp"
"C:\Qt\6.8.3\msvc2022_64\bin\moc.exe" "include\audio_capture.h" -o "src\moc_audio_capture.cpp" 
"C:\Qt\6.8.3\msvc2022_64\bin\moc.exe" "include\output_corrector.h" -o "src\moc_output_corrector.cpp" 